### ISSUE TITLE
Parameters lookup for ActiveJob descendants

### ISSUE THREAD

**Issue by gohkhoonhiang** [gohkhoonhiang/sidekiq_adhoc_job#21]
In Rails, all jobs inherit from ActiveJob, and when Sidekiq Adhoc Job tries to inspect the parameters list from the chain of ancestors, it reaches ActiveJob#perform and only get a rest argument.

The solution for this is to explicitly lookup the parameters from the first prepended module.

**Comment by gohdaniel15** [comment]
Hey @gohkhoonhiang, thanks for opening an issue for this. I've done some digging myself, and found the same cause as you did. Specifically, Rails will go up to `ActiveJob::Execution.perform(*)` and inspect the parameters there. 

https://github.com/gohkhoonhiang/sidekiq_adhoc_job/blob/ac5b6cd79a835a26c0e67cfebc5659ab0ca8d15a/lib/sidekiq_adhoc_job/utils/class_inspector.rb#L42-L46

Quick question, I'm not sure
1. Which circumstances do we want to go up the method chain, and
2. Which circumstances do we want to use the first method in the method chain? (e.g is it only for Rails?)
